### ISSUE TITLE
value definition for prompts

### ISSUE THREAD

**Issue by founderlin** [KMnP/vpt#11]
https://github.com/KMnP/vpt/blob/94e5be7bddf7a398729c127928a50384b42e95f5/src/models/vit_prompt/vit_mae.py#L34

Hello! The value defined in the line above seems not distinctly elaborated in the paper. Could you explain the reason why you define the value in this way? Many thx in advance.

**Comment by KMnP** [comment]
Hi, thanks for your question. 

That `val` is used for prompt initialization with xavier_uniform initialization (Appendix A.1)

**Comment by founderlin** [comment]
I found the Appendix after typing the question. Many thx.
