### ISSUE TITLE
when applying prompt to SETR, where can we get the pretrained model 'ViT-L'?

### ISSUE THREAD

**Issue by 1Yanxiaolin1** [KMnP/vpt#12]
thanks to your impressive work!
![55c733bb8c0cbdc29fc77330defb819](https://user-images.githubusercontent.com/92147117/193209367-d9db9591-5f1c-425d-93a6-55bbf61595f0.jpg)
You use mmseg in your segmentation part. The ViT-L backbone is supervisely pre-trained on ImageNet-21k. However, we can't find the pretraining weights in mmseg. 
![487a70977366638f7ed7207b31adf9b](https://user-images.githubusercontent.com/92147117/193210284-d7403f58-32b9-4a14-a34e-632af378e147.jpg)
so how to get the pretraining weights aboout ViT-L in mmseg? thanks!

**Comment by Tsingularity** [comment]
I think I followed the instructions [here](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/setr) when setting up the segmentation experiment. Could u please take a look? Feel free to let me know if u have more questions.
