### ISSUE TITLE
Total tunable parameters

### ISSUE THREAD

**Issue by 111chengxuyuan** [KMnP/vpt#17]
![image](https://user-images.githubusercontent.com/53029965/196077899-bb01d24e-eb5a-4751-887e-8ac1bf6996cc.png)
Hello, I'd like to ask you a quesetion, what is the unit of the "Total params" in the experiment table? is it "M"? For example, the "Total params" of VPT-deep is 1.18x, does it mean 1.18M?

**Comment by Charleshhy** [comment]
You can refer to https://github.com/KMnP/vpt/issues/10. "Total params" is the number of params including backbone and the other trainable parameters for a total of 19 (VTAB) + 5 (FGVC) tasks.

**Comment by KMnP** [comment]
Let me know if you have other questions!

**Comment by KMnP** [comment]
Close this issue for now. Feel free to re-open it if you have other questions!

**Comment by ChengHan111** [comment]
Hi, I am wondering if there is a specific reason to include a backbone param within VPT total param calculation. I am getting a little bit confused by calculated with one backbone param + the other trainable parameters

**Comment by Tsingularity** [comment]
@ChengHan111 "Total Params" here refers to all the parameters we need to store for all the 24 downstream classification tasks. Since VPT doesn't modify the backbone params, we only need to store one copy of it. Full-finetuning will need to store 24 finetuned copies.

**Comment by ChengHan111** [comment]
> ation tasks. Since VPT doesn't modify the backbone params, we only need to store one copy of it. Full-finetuning

Thanks! Now I get it.
