### ISSUE TITLE
How to apply data augmentation for VTAB

### ISSUE THREAD

**Issue by kai-wen-yang** [KMnP/vpt#18]
Hi, I want to apply some data augmentation using torchvision.transform for VTAB dataset.
Does your repo support that? If yes, how to implement it?
Thanks a lot!

**Comment by KMnP** [comment]
Hi, we don't support more augmentation techniques in this repo, following practices of original [VTAB](https://github.com/google-research/task_adaptation/blob/master/task_adaptation/data_loader.py) paper. 

But you can add your own inside this function:  https://github.com/KMnP/vpt/blob/main/src/data/datasets/tf_dataset.py#L148
