### ISSUE TITLE
All results for each dataset in Vtab-1k

### ISSUE THREAD

**Issue by xiaohhuiiiii** [KMnP/vpt#19]
Hello, I want to konw if you have all results for each dataset with CNN, because I am researching about the prompt learning with CNN. If you have these, I will be thankful.

**Comment by KMnP** [comment]
Hi, you could find the results in the provided links [here](https://github.com/KMnP/vpt#hyperparameters-for-experiments-in-paper). If you click on the file named `vtab_all_release.csv`, you could find results with CNN there, with feature == "imagenet22k_sup_rnx_base" or "imagenet_sup_rn50".

Let me know if you have any other questions!

**Comment by xiaohhuiiiii** [comment]
Thank you very much, I have got what I want, thank you for your answer
