### ISSUE TITLE
cfg.DIST_INIT_PATH = "tcp://{}:12399".format(os.environ["SLURMD_NODENAME"])

### ISSUE THREAD

**Issue by Henkwu** [KMnP/vpt#20]
![image](https://user-images.githubusercontent.com/73421644/200988277-7ae4a414-865a-4d7a-b302-2be4472eec06.png)

**Comment by Henkwu** [comment]
How to solve this error please? thanks

**Comment by loopyli** [comment]
@Henkwu Hi,have you solved this problem? I have also encountered this problem, but I don't have a good way to solve it.Could you help me?

**Comment by muziht** [comment]
> h

注释它
