### ISSUE TITLE
core dumped ?

### ISSUE THREAD

**Issue by Henkwu** [KMnP/vpt#22]
![image](https://user-images.githubusercontent.com/73421644/201026481-055f0c31-b498-4975-90fe-db5da9ae4412.png)
What does this error mean please? how to solve it, thanks

**Comment by KMnP** [comment]
Does it happen again? could you replicate this error?

**Comment by Henkwu** [comment]
The code does not work properly. This error persists.

**Comment by KMnP** [comment]
if the error persists, I recommend that you reduce your batchsize.

**Comment by wangdaha1** [comment]
> ![image](https://user-images.githubusercontent.com/73421644/201026481-055f0c31-b498-4975-90fe-db5da9ae4412.png) What does this error mean please? how to solve it, thanks

Hi, I met the same problem when I try to run demos for vtab dataset. Have you solved it? Thanks!
