### ISSUE TITLE
How to process VTAB

### ISSUE THREAD

**Issue by wangdaha1** [KMnP/vpt#27]
Hi, I am seeking for help about processing VTAB datasets.

Since it is not convenient for me to directly run your code to download vtab dataset, I borrow the extracted vtab datasets from others, where each file folder (19 datasets in total) contains the following files:
```
images
--train800
----000000.jpg
----000001.jpg
...
--train800val200
--val200
--test
test.txt
train800.txt
train800val200.txt
val200.txt
```
, where *.txt contains image path and label such as 'images/train800/000000.jpg 307'. Is this the correct format of the data needed?

Further, even though I have the data, when I run your code, it still tried to download the data using tf, which is intractable for me. Hence, I wonder is there any way for me to run your code when I already have the data (if correct)?

Thanks!

**Comment by KMnP** [comment]
Our code use tfds package, which takes in processed tfrecord file. not raw jpg. My suggestions are to write your own data class, or convert these file to tfrecord.

**Comment by guobabaya** [comment]
> 您好，我正在寻求有关处理 VTAB 数据集的帮助。
> 
> 由于我不方便直接运行你的代码下载vtab数据集，我借用了别人提取的vtab数据集，每个文件夹（共19个数据集）包含以下文件：
> 
> ```
> images
> --train800
> ----000000.jpg
> ----000001.jpg
> ...
> --train800val200
> --val200
> --test
> test.txt
> train800.txt
> train800val200.txt
> val200.txt
> ```
> 
> ，其中 *.txt 包含图像路径和标签，例如“images/train800/000000.jpg 307”。这是所需数据的正确格式吗？
> 
> 此外，即使我有数据，当我运行你的代码时，它仍然尝试使用 tf 下载数据，这对我来说很棘手。因此，我想知道当我已经有了数据（如果正确的话）时，我有什么办法可以运行你的代码吗？
> 
> 谢谢！

你好，我的网络也不允许我使用tfds的api下载，我想知道你后续成功运行起来了吗，可以给我一些帮助吗?

**Comment by KantLru** [comment]
你好，请问你解决了吗？我现在也遇见了无法执行数据下载

**Comment by KantLru** [comment]
> > 您好，我正在寻求有关处理 VTAB 数据集的帮助。
> > 由于我不方便直接运行你的代码下载vtab数据集，我借用了别人提取的vtab数据集，每个文件夹（共19个数据集）包含以下文件：
> > ```
> > images
> > --train800
> > ----000000.jpg
> > ----000001.jpg
> > ...
> > --train800val200
> > --val200
> > --test
> > test.txt
> > train800.txt
> > train800val200.txt
> > val200.txt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ，其中 *.txt 包含图像路径和标签，例如“images/train800/000000.jpg 307”。这是所需数据的正确格式吗？
> > 此外，即使我有数据，当我运行你的代码时，它仍然尝试使用 tf 下载数据，这对我来说很棘手。因此，我想知道当我已经有了数据（如果正确的话）时，我有什么办法可以运行你的代码吗？
> > 谢谢！
> 
> 你好，我的网络也不允许我使用tfds的api下载，我想知道你后续成功运行起来了吗，可以给我一些帮助吗?

你好，您的数据读取了没有？我也遇见了数据下载的问题
