### ISSUE TITLE
The initialization of prompt

### ISSUE THREAD

**Issue by qianlanwyd** [KMnP/vpt#3]
May I ask why prompt is initialized like this?
https://github.com/KMnP/vpt/blob/main/src/models/vit_prompt/vit.py#L57

**Comment by KMnP** [comment]
Hi, thanks for the question! We tried different initialization methods for prompt in Appendix B, Fig. 13. To our surprise,  default random initialization works the best in general,  in contrast to comparable studies in NLP. 

As for why we randomly initialize prompts with xavier uniform initialization scheme, we follow the initialization of linear layers of ViT in [MAE](https://github.com/facebookresearch/mae/blob/main/models_mae.py) and JAX ViT. The intuition is that prompts actually act as an "additional filter" for the image patches in ViT.

**Comment by qianlanwyd** [comment]
Thanks for your prompt reply.
