### ISSUE TITLE
KeyError: "Trying to access `splits['train']` but `splits` is empty. This likely indicate the dataset has not been generated yet."

### ISSUE THREAD

**Issue by fenglincong** [KMnP/vpt#32]
![image](https://user-images.githubusercontent.com/90673560/224671163-fbe6c1fd-c363-4cae-bef2-3ffc3e769680.png)

**Comment by KMnP** [comment]
Hi, please follow the direction https://github.com/KMnP/vpt#datasets-preperation to download the split info.
