### ISSUE TITLE
Stanford Cars dataset split

### ISSUE THREAD

**Issue by andrewjywang** [KMnP/vpt#37]
I am unable to download the StanfordCars database from the official source. The provided download link (http://ai.stanford.edu/~jkrause/cars/car_dataset.html) is currently not accessible. It seems that the URL is either outdated or the database is no longer publicly available. Could you kindly provide an alternative download source?

Additionally, I have come across a shared version of the StanfordCars database from another user. However, I noticed that the name of each image in this shared database does not match the split (train, test, validation) in the dataset documentation. It would be greatly appreciated if split information could be provided or how to build the split.

Thank you for your understanding and support.

**Comment by dercaft** [comment]
I am faced with same issue, looking forward a solution.

**Comment by pgsld23333** [comment]
This dataset can be downloaded from there. https://github.com/cyizhuo/Stanford-Cars-dataset
I have been looking for a long time and really appreciate the provider.

**Comment by KMnP** [comment]
close the issue since @pgsld23333 solved the problem. Feel free to re-open if there are more questions

**Comment by KMnP** [comment]
@andrewjywang  in terms of the mapping from original stanford car images to the new source, the image_ids are all the same in my understanding. you could still use the same image name, and remove `car_ims/` in the split json files provided.
