### ISSUE TITLE
What is the use of grid search

### ISSUE THREAD

**Issue by ruanchunqing7** [KMnP/vpt#41]
Hi,

Thanks for the great work!

<img width="945" alt="image" src="https://github.com/KMnP/vpt/assets/55775666/d8a03b5b-6bea-4904-b9c2-4365279411e9">

In tune_vtab.py, I noted the code above. I am confused the use of the code, since the best lr and wd are not saved for final 5 times.

Kind regards,

**Comment by pgsld23333** [comment]
Hello, I have the same confusion, can you tell me why this is？ #

> Hi,
> 
> Thanks for the great work!
> <img alt="image" width="945" src="https://user-images.githubusercontent.com/55775666/243078185-d8a03b5b-6bea-4904-b9c2-4365279411e9.png">
> 
> In tune_vtab.py, I noted the code above. I am confused the use of the code, since the best lr and wd are not saved for final 5 times.
> 
> Kind regards,

**Comment by pgsld23333** [comment]
Oh I see, when final_runs is set to True, the setup function will automatically find the optimal learning rate and weight_decay through the function find_best_lrwd
