### ISSUE TITLE
CUB dataset

### ISSUE THREAD

**Issue by sczustc** [KMnP/vpt#52]
I downloaded the CUB dataset, but there is no train.json in it. How can I obtain this file,

**Comment by GrantorShadow** [comment]
Hi!
Please check the drop box associated with the dataset.
Link - https://cornell.app.box.com/v/vptfgvcsplits

**Comment by sczustc** [comment]
Thank you for your answer. After raising the issue, I discovered a solution. It may be due to network issues that prevented access. Now I can run through the code, and your paper has been very helpful to me. Through your code, I have mastered the details of the paper and successfully ported it to other network structures and fields. Thanks a lot!
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KMnP/vpt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月30日(星期一) 晚上10:15
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [KMnP/vpt] CUB dataset (Issue #52)





 
Hi!
 Please check the drop box associated with the dataset.
 Link - https://cornell.app.box.com/v/vptfgvcsplits

**Comment by EmpireShadow** [comment]
Excuse me, can you share the json file? Now this link（https://cornell.app.box.com/v/vptfgvcsplits ） is no longer valid, thank you!
