### ISSUE TITLE
How to train successfully in Cifar100

### ISSUE THREAD

**Issue by miss-rain** [KMnP/vpt#9]
**I have tried a long time for training Cifar100, but it still does not work. please help me to run successfully, thanks very much!**

**1.Have downloaded the Cifar100 dataset:**
<img width="423" alt="1660829391508" src="https://user-images.githubusercontent.com/17979331/187202179-388526ae-9885-461e-b407-41a0633e7f53.PNG">

**2.Have downloaded the pretrained_model and rename**
<img width="353" alt="1660829299011" src="https://user-images.githubusercontent.com/17979331/187202445-850439b2-b85c-44e6-8744-b1b08fc55d48.PNG">

**3.Configs file:
vpt/configs/prompt/cifar100.yaml**
<img width="556" alt="1660829612675" src="https://user-images.githubusercontent.com/17979331/187202520-ec415803-774f-4826-ab1f-b7d42b4348a7.PNG">

**Configs file:
vpt/src/configs/config.py**
<img width="944" alt="1660829798311" src="https://user-images.githubusercontent.com/17979331/187202912-17401471-ea97-47cc-8867-2cefbb1c93d1.PNG">

**4.Train model:
/vpt/run.sh**
<img width="477" alt="1660829880467" src="https://user-images.githubusercontent.com/17979331/187203185-784725df-c1f0-48b4-b074-7c7619b871fb.PNG">

**5. Error log**
<img width="1179" alt="W" src="https://user-images.githubusercontent.com/17979331/187204662-e3a68e04-1192-489f-ac89-3a687e3b90c7.PNG">

**Comment by KMnP** [comment]
Hi, thanks for your interest in our work! we use CIFAR-100 from VTAB-1k suits. So I recommend to follow instructions from: https://github.com/KMnP/vpt/blob/main/VTAB_SETUP.md. 

Let me know if you have other questions!

**Comment by miss-rain** [comment]
Thanks !
I try again, and i found in **/vpt/src/data/loader.py  line 32 : from .datasets.tf_dataset import TFDataset**,  it does not work
![Snipaste_2022-09-02_11-17-05](https://user-images.githubusercontent.com/17979331/188052037-fa7d1d2c-d0bd-4747-a2b7-138e95e4f434.png)

By a way , **how to get json file for other datasets, like StanfordCars**

Thank again !

**Comment by KMnP** [comment]
Hi, could you tell me more about the error? For example,  if there is no error report, how did you know this line is the issue? Have you installed tfds?

As for the second question, you can find links to the JSON files here: https://github.com/KMnP/vpt#datasets-preperation

**Comment by Tsingularity** [comment]
@miss-rain
